### ISSUE TITLE
Metadata version mismatch in production build

### ISSUE THREAD

**Issue by isuruhettiarachchi** [antonio-spinelli/ionic-logger#3]
Following error comes when try `ionic cordova run android --prod`

`Error: Metadata version mismatch for module C:/Ionic/Ionic-Sample/node_modules/ionic-logger/dist/es2015/src/mod
ule.d.ts, found version 4, expected 3
    at StaticSymbolResolver.getModuleMetadata (C:\Ionic\Ionic-Sample\node_modules\@angular\compiler\bundles\com
piler.umd.js:25748:34)
    at StaticSymbolResolver._createSymbolsOf (C:\Ionic\Ionic-Sample\node_modules\@angular\compiler\bundles\comp
iler.umd.js:25536:46)
    at StaticSymbolResolver.getSymbolsOf (C:\Ionic\Ionic-Sample\node_modules\@angular\compiler\bundles\compiler
.umd.js:25517:14)
    at C:\Ionic\Ionic-Sample\node_modules\@angular\compiler\bundles\compiler.umd.js:24376:30
    at Array.forEach (<anonymous>)
    at extractProgramSymbols (C:\Ionic\Ionic-Sample\node_modules\@angular\compiler\bundles\compiler.umd.js:2437
5:79)
    at AotCompiler.analyzeModulesAsync (C:\Ionic\Ionic-Sample\node_modules\@angular\compiler\bundles\compiler.u
md.js:23931:47)
    at CodeGenerator.codegen (C:\Ionic\Ionic-Sample\node_modules\@angular\compiler-cli\src\codegen.js:32:14)
    at Function.NgTools_InternalApi_NG_2.codeGen (C:\Ionic\Ionic-Sample\node_modules\@angular\compiler-cli\src\
ngtools_api.js:73:30)
    at C:\Ionic\Ionic-Sample\node_modules\@ionic\app-scripts\dist\aot\aot-compiler.js:182:73`

**Comment by antonio-spinelli** [comment]
I'm not able to reproduce your issue. Did you try a clean npm install? Maybe something is broken in your node_modules folder.

**Comment by isuruhettiarachchi** [comment]
Bug was due to a angular version mismatch. I updated the angular packages and it worked.
